### ISSUE TITLE
add tiktok option

### ISSUE THREAD

**Issue by danchengash** [AbhishekDoshi26/contactus#14] opened 2023-07-20 13:00 UTC

**Comment by Shreemanarjun** [comment] 2023-10-03 12:56
@AbhishekDoshi26 I want to work on this. Please assign me.

**Comment by AbhishekDoshi26** [comment] 2023-10-05 18:08
@Shreemanarjun sure go on :)

**Comment by Shreemanarjun** [comment] 2023-10-10 04:17
Fixed by #15 @AbhishekDoshi26

**Comment by Shreemanarjun** [comment] 2023-10-10 06:50
Please assign the bug label to hacktoberfest if possible.

**Comment by Imsurajr** [comment] 2023-10-10 18:15
If the issue is still open, i will like to work on it.

**Comment by AbhishekDoshi26** [comment] 2023-10-10 18:18
Fixed in #15

**Closed as completed by AbhishekDoshi26** 2023-10-10 18:18 UTC
Labels: enhancement, hacktoberfest
